
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  database: swiit_rails_development
  host: localhost
  port: 5432

test:
  <<: *default
  adapter: postgresql
  database: swiit_rails_test

production:
  <<: *default
  database: swiit_rails_production
  username: swiit_rails
  password: <%= ENV['SWIIT_RAILS_DATABASE_PASSWORD'] %>


  